"""SG POC pipeline.

  python3 -m sgpipe.cli run                 # seed -> generate -> transform -> push
  python3 -m sgpipe.cli run --trigger       # ...and fire the mabl plans, then gate
  python3 -m sgpipe.cli run --dry-run       # everything except the mabl writes
  python3 -m sgpipe.cli run --offline       # bundled seed fixture, no mabl read

Stages can also be run one at a time (seed / generate / transform / push /
trigger); each reads the previous stage's file out of ./out.
"""
import argparse
import concurrent.futures
import datetime
import json
import os
import sys

from . import config, sources, transform
from .mabl import Mabl, MablError

FIXTURE_SEED = os.path.join(config.ROOT, "fixtures", "seed_rows.json")


def _write(name, payload):
    path = os.path.join(config.out_dir(), name)
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2)
    return path


def _read(name):
    path = os.path.join(config.out_dir(), name)
    if not os.path.exists(path):
        sys.exit("missing %s - run the earlier stage first" % path)
    with open(path) as fh:
        return json.load(fh)


def _client(cfg):
    """Editor key - seed read and DataTable writes."""
    return Mabl(config.api_key(), cfg["workspace_id"])


def _deploy_client(cfg):
    """Deployment Trigger / CI-CD key - firing plans and reading results."""
    return Mabl(config.deploy_key(), cfg["workspace_id"])


def _run_id(explicit=None):
    if explicit:
        return explicit
    return datetime.datetime.utcnow().strftime("%Y-%m-%d_%H-%M-%S")


# ---------------------------------------------------------------- stage 01
def stage_seed(cfg, args):
    print("[01] seed rows")
    if args.offline:
        rows = json.load(open(FIXTURE_SEED))
        print("     %d rows from the bundled fixture" % len(rows))
    else:
        client = _client(cfg)
        table_id = cfg["seed"]["data_table_id"]
        scenarios = client.get_scenarios(table_id)
        rows = [{v["name"]: v.get("value", "") for v in (s.get("variables") or [])}
                for s in scenarios]
        print("     %d rows read live from mabl table %s" % (len(rows), table_id))
    if not rows:
        sys.exit("no seed rows - nothing to do")
    _write("seed.json", rows)
    return rows


# ---------------------------------------------------------------- stage 02
def stage_generate(cfg, args, rows=None):
    rows = rows if rows is not None else _read("seed.json")
    run_id = args.run_id
    jitter = cfg["mock"].get("price_jitter_pct", 6)
    dupes = cfg["mock"].get("duplicate_options", 0)
    print("[02] getRates (mocked), %d seed rows in parallel" % len(rows))

    records = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        futures = {
            pool.submit(sources.fetch_rates, row, run_id, jitter, dupes): row
            for row in rows
        }
        for fut in concurrent.futures.as_completed(futures):
            row = futures[fut]
            batch = fut.result()
            print("     Tc_id %-3s %-18s -> %2d options"
                  % (row.get("Tc_id", "?"), row.get("vin", "?"), len(batch)))
            records.extend(batch)

    records.sort(key=lambda r: (str(r.get("seedTcId")), r.get("optionId")))
    print("     %d raw records collected in ONE list (not one table per iteration)"
          % len(records))
    _write("raw.json", records)
    return records


# ---------------------------------------------------------------- stage 03
def stage_transform(cfg, args, records=None):
    records = records if records is not None else _read("raw.json")
    print("[03] filter / dedupe / merge")
    report = transform.prepare(records, cfg["filter"], sources.dealer_lookup())
    print("     raw %d -> filtered %d (%s) -> unique %d -> valid %d"
          % (report["raw"], report["filtered"],
             "+".join(cfg["filter"]["include_product_codes"]),
             report["deduped"], len(report["rows"])))
    if report["rejected"]:
        print("     %d rejected (see out/rejects.json)" % report["rejected"])
        _write("rejects.json", report["rejects"])
    _write("api_rows.json", report["rows"])
    _write("ui_rows.json", report["rows"])
    verify = transform.verify_rows(report["rows"])
    _write("verify_rows.json", verify)
    print("     %d vehicle row(s) for the GetRates verification test" % len(verify))
    return report["rows"]


# ---------------------------------------------------------------- stage 04
def stage_push(cfg, args, rows=None):
    rows = rows if rows is not None else _read("api_rows.json")
    targets = [
        (cfg["targets"]["api_table_name"], transform.API_COLUMNS,
         "API chain input - generated by SG-POC-Pipeline"),
        (cfg["targets"]["ui_table_name"], transform.UI_COLUMNS,
         "Portal test input - generated by SG-POC-Pipeline"),
        (cfg["targets"]["verify_table_name"], transform.VERIFY_COLUMNS,
         "GetRates verification input - one row per vehicle"),
    ]
    print("[04] push to mabl")
    verify = transform.verify_rows(rows)

    def _source(columns):
        if columns is transform.VERIFY_COLUMNS:
            return verify, "Vehicle"
        return rows, "Rate"

    if args.dry_run:
        for name, columns, _ in targets:
            src, _prefix = _source(columns)
            print("     DRY RUN %s: %d rows x %d columns" % (name, len(src), len(columns)))
        return []

    client = _client(cfg)
    summary = []
    for name, columns, description in targets:
        source, prefix = _source(columns)
        scenarios = transform.to_scenarios(source, columns, prefix)
        res = client.upsert_table(name, scenarios, columns, description)
        print("     %s  %s  (%s)"
              % (name, res["id"], "created" if res["created"] else "existing"))
        if res["columns_added"]:
            print("       + %d column(s): %s"
                  % (len(res["columns_added"]), ", ".join(res["columns_added"])))
        print("       %s to %d rows (1 call, not %d POSTs)"
              % ("created" if res["created"] else "reconciled",
                 res["rows"], len(scenarios)))
        summary.append({"name": name, "id": res["id"], "rows": res["rows"],
                        "columns": len(columns), "created": res["created"],
                        "url": "https://app.mabl.com/workspaces/%s/configuration/data-tables/%s"
                               % (cfg["workspace_id"], res["id"])})
    _write("push_summary.json", summary)
    return summary


# ---------------------------------------------------------------- stage 05
def stage_trigger(cfg, args):
    trig = cfg["trigger"]
    print("[05] trigger mabl plans %s" % (trig["plan_labels"] or "(any deployment-triggered plan)"))
    # --preview never executes a plan, so it stays useful under --dry-run:
    # it is the only way to exercise MABL_DEPLOY_KEY without running tests.
    if args.dry_run and not args.preview:
        print("     DRY RUN - no deployment event")
        return 0
    client = _deploy_client(cfg)
    event = client.deployment_event(
        trig["application_id"], trig["environment_id"], trig["plan_labels"],
        revision=os.environ.get("GITHUB_SHA"), preview=args.preview)
    if args.preview:
        print("     preview: %s" % json.dumps(event)[:800])
        return 0
    event_id = event.get("id")
    triggered = event.get("triggered_plan_run_summaries") or []
    print("     event %s -> %d plan run(s)" % (event_id, len(triggered)))
    if not triggered:
        print("     ! no plans matched those labels in that environment")
        return 1

    result = client.wait_for_event(event_id, trig["poll_interval_seconds"],
                                  trig["poll_timeout_seconds"])
    status = (result or {}).get("event_status") or {}
    if status.get("succeeded"):
        print("     PASS")
        return 0
    analysis = (result or {}).get("failure_analysis") or {}
    if analysis.get("headline"):
        print("     %s" % analysis["headline"])
    for ex in (result or {}).get("executions") or []:
        for je in ex.get("journey_executions") or []:
            if not je.get("success"):
                print("     FAIL %s" % (je.get("journey", {}).get("name") or je.get("id")))
    print("     FAIL")
    return 1


# ---------------------------------------------------------------- main
STAGES = {"seed": 1, "generate": 2, "transform": 3, "push": 4, "trigger": 5}


def main(argv=None):
    parser = argparse.ArgumentParser(prog="sgpipe", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("stage", choices=list(STAGES) + ["run"])
    parser.add_argument("--run-id", default=None,
                        help="label stamped onto every row; defaults to a UTC timestamp")
    parser.add_argument("--offline", action="store_true",
                        help="use the bundled seed fixture instead of reading mabl")
    parser.add_argument("--dry-run", action="store_true",
                        help="do everything except write to mabl")
    parser.add_argument("--trigger", action="store_true",
                        help="with 'run': also fire the plans and gate on the result")
    parser.add_argument("--preview", action="store_true",
                        help="with 'trigger': resolve which plans would run, without running")
    args = parser.parse_args(argv)
    args.run_id = _run_id(args.run_id)

    cfg = config.load_config()
    print("run_id %s   workspace %s" % (args.run_id, cfg["workspace_id"]))
    print("")

    try:
        if args.stage == "seed":
            stage_seed(cfg, args)
        elif args.stage == "generate":
            stage_generate(cfg, args)
        elif args.stage == "transform":
            stage_transform(cfg, args)
        elif args.stage == "push":
            stage_push(cfg, args)
        elif args.stage == "trigger":
            return stage_trigger(cfg, args)
        else:
            rows = stage_seed(cfg, args)
            raw = stage_generate(cfg, args, rows)
            prepared = stage_transform(cfg, args, raw)
            summary = stage_push(cfg, args, prepared)
            code = stage_trigger(cfg, args) if args.trigger else 0
            print("")
            for t in summary:
                print("  %s  %d rows  %s" % (t["name"], t["rows"], t["url"]))
            return code
    except MablError as exc:
        print("\nmabl API error:\n%s" % exc, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
